import = ["colors/vscode_terminal.toml"]
live_config_reload = true

[colors.primary]
background = "#181818"

[window]
decorations = "Full"
opacity = 1
startup_mode = "Maximized"
padding = { x = 0, y = 5 }

[env]
TERM = "alacritty"


[bell]
color = "#003300"
duration = 32

[font]
size = 10
offset = { x = 0, y = 0 }
normal      = { family = "FiraCode Nerd Font", style = "Regular" }
bold        = { family = "FiraCode Nerd Font", style = "Bold" }
italic      = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
	{ chars = "\u001F", key = "Slash", mods = "Control" },
	{ chars = "\u001F", key = "Slash", mods = "Control|Shift" },
	{ chars = "\u0000", key = "Space", mods = "Control" },
	{ action = "None", key = "W", mods = "Command" },
	{ action = "ToggleFullscreen", key = "Return", mods = "Command" },
	{ action = "SpawnNewInstance", key = "N", mods = "Command" }
]
